ideapeacher/urls.py
from django.urls import path
from . import views
app_name = "ideapeacher"
urlpatterns = [

	path('peacher/', views.registerPeacher, name="register" ),
	path('login_request/',views.login_request,name="login_request" ),
	path('home/',views.ideapeacherpage,name="home" ),
	path('logout_request/',views.logout_request,name="logout" ),
	path('home_sponser/',views.sponserPage,name="home_sponser"),
	path('submitidea/',views.submitidea,name="submitidea"),
	path('idea/',views.post,name="post"),
	path("comment/<int:pk>/",views.comment,name="comment"),
	path("edit_idea/<int:pk>/",views.edit_idea,name="edit_idea"),
	path("updateidea/<int:pk>/",views.updateidea,name="updateidea"),
	path("deleteidea/<int:pk>/",views.deleteidea,name="deleteidea"),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ideapeacher.urls')),
    path('',include('sponser.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sponser/urls.py
from django.urls import path,include
from . import views

urlpatterns = [

    path('sponser/',views.registerSponser,name="register"),

]

ideapeacher/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.


class ideapeacher(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)


class category(models.Model):
    category = models.CharField(max_length=100)


class idea(models.Model):
    peacher = models.ForeignKey(
        ideapeacher, on_delete=models.CASCADE, default=None)
    post_idea = models.TextField()
    date_created = models.DateTimeField(default=datetime.now())
    category = models.ManyToManyField(category)

    pdf = models.FileField(upload_to="book/pdfs", blank=True)

    def __str__(self):
        return self.post_idea

class Public(models.Model):
    comment = models.TextField()
    date_created = models.DateTimeField(default=datetime.now())
    on_post = models.ForeignKey(idea,on_delete=models.CASCADE,default=None)
    by = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.comment

sponser/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class sponser(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)

ideapeacher/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = {'username', 'email', 'password1', 'password2'}

ideapeacher/views.py
from datetime import datetime
import re
from django.contrib import auth
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect

from . models import Public, idea, ideapeacher,category
from . decorators import ideapeacher_only,allowed_users
from django.http import HttpResponse, request
from django.contrib import messages
from .forms import CreateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def registerPeacher(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            if not Group.objects.filter(name="ideapeacher").exists():
                group = Group.objects.create(name="ideapeacher")
                addtogroup = Group.objects.get(name='ideapeacher')
                user.groups.add(addtogroup)

                ideapeacher.objects.create(user=user, name=user.username )
                messages.success(request, 'Account was created for '+ username)
                return redirect('/login_request/')
            else:
                   group = Group.objects.get(name='ideapeacher')
                   user.groups.add(group)
                   ideapeacher.objects.create(user=user, name=user.username )
                   messages.success(request, 'Account was created for '+ username)
                   return redirect('/login_request/')

    context = {'form': form}

    return render(request, 'main/register.html', context)

def login_request(request):
	if request.method == 'POST':
		username = request.POST.get("username")
		password = request.POST.get("password")

		user = authenticate(request,username=username,password=password)
		if user is not None:
			login(request,user)
			return redirect('/home')
		
		else:
			messages.info(request,"Username or password is incorrect!")
	

	return render(request,"main/login.html")


def logout_request(request):
	logout(request)
	return redirect('/login_request/')


def ideapeacherpage(request):
    i = idea.objects.all()
    b = Public.objects.all()
    return render(request,"main/home.html",{"ideas":i,'comments':b})


@allowed_users(allowed_roles=['sponser'])	
def sponserPage(request):
	u=ideapeacher.objects.all()
	i= idea.objects.all()
	return render(request,"main/home1.html",{"ideas":i, "user":u})


@allowed_users(allowed_roles=['ideapeacher'])
def submitidea(request):
    if request.method == 'POST':
        c=request.POST.get("dropdown")

        if not category.objects.filter(category=c).exists():
            rp = category(category=c)
            rp.save()

            i= request.POST.get("idea")
            u= ideapeacher.objects.get(user=request.user)
            p=request.FILES.get("pdf")

            d=datetime.now()

            post = idea(peacher=u,post_idea=i,date_created=d,pdf=p)
            post.save()
            post.category.add(rp)
            return redirect("/home")

        else:
            cp = category.objects.get(category=c)
            i= request.POST.get("idea")
            u= ideapeacher.objects.get(user=request.user)
            p=request.FILES.get("pdf")

            d=datetime.now()
            post = idea(peacher=u,post_idea=i,date_created=d,pdf=p)
            post.save()
            post.category.add(cp)

    return  redirect("/home")

@ideapeacher_only
def post(request):
    return render(request,"main/idea.html")


def comment(request,pk):
    if request.method == 'POST':
        f = idea.objects.get(pk=pk)
        i = request.POST.get("comment")

        u = request.user
        d = datetime.now()

        post = Public(comment=i,date_created=d,on_post=f,by=u )
        post.save()

    return redirect("/home")

@allowed_users(allowed_roles=['ideapeacher'])
def edit_idea(request,pk):
    i = idea.objects.get(pk=pk)
    context = {
        'share':i
    }

    return render(request,"main/edit.html",context)

@allowed_users(allowed_roles=['ideapeacher'])
def updateidea(request,pk):
    i= idea.objects.get(pk=pk)
    i.post_idea=request.POST.get("idea")
    i.save()
    return redirect('/home')


@allowed_users(allowed_roles=['ideapeacher'])
def deleteidea(request,pk):
    i= idea.objects.get(pk=pk)
    i.delete()
    return redirect('/home')

sponser/views.py
from django.shortcuts import redirect, render
from ideapeacher.forms import CreateUserForm
from django.contrib.auth.models import Group
from django.contrib import messages
from django.http import HttpResponse
from . models import sponser
from django.contrib.auth import authenticate, login, logout
# Create your views here.


def registerSponser(request):
    form = CreateUserForm()
    if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data.get('username')

                if not Group.objects.filter(name="sponser").exists():
                    group = Group.objects.create(name="sponser")
                    addtogroup = Group.objects.get(name='sponser')
                    user.groups.add(addtogroup)

                    sponser.objects.create(user=user, name=user.username)
                    messages.success(
                    request, 'Account was created for ' + username)
                    return redirect('/login_request1/')

                else:
                    group = Group.objects.get(name='sponser')
                    user.groups.add(group)
                    sponser.objects.create(user=user, name=user.username)
                    messages.success(
                    request, 'Account was created for ' + username)
                    return redirect('/login_request1/')

    context = {'form': form}

    return render(request, 'main/register.html', context)

ideapeacher/templates/main/edit.html
{% extends "main/header.html" %}

{% block content %}

<form method="post" action="{% url 'ideapeacher:updateidea' share.pk %}">
	{% csrf_token %}
	<textarea class="form-control" aria-label="With textarea" name="idea">{{share.post_idea}}</textarea>

	<button type="submit" class="btn btn-success">Update</button>

</form>
{% endblock %}

ideapeacher/templates/main/header.html
<head>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            

</head>

<body>
	<!--nav bar -->

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">IdeaPeacher.com</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      
        {% if user.is_authenticated %}
        <li> Logged in as {{ user.username|title }}</li>
        <li><a href="/logout_request">Logout</a></li>
        {% else %}
        <li><a href="/login_request">Login</a></li>
        <li><a href="/peacher">Register</a></li>
        {% endif %}
        <li><a href="/idea">Post</a></li>
      </ul>
    </div>
  </nav>
        

<div class="container" id="frontend">
	
	{% block content %}

	{% endblock %}
</div>


</body>

ideapeacher/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}

{% if ideas %}

{% for i in ideas %}
<p>User: {{i.peacher.user}}</p>
<p>{{i.date_created}}</p>

{% for c in i.category.all %}
	{{c.category}}

	<div>
		
		<a href="{% url 'ideapeacher:edit_idea' i.pk %}">Edit</a>
		<a href="{% url 'ideapeacher:deleteidea' i.pk %}">Delete</a>
	</div>

	<p>{{i.post_idea}}</p>
	
<div>Comments:</div>

{% for b in comments %}
{% ifequal i.id b.on_post.id %}

<p>{{b.by}}: {{b.comment}}</p>

{% endifequal %}
{% endfor %}

<!-- make a comment box -->
<form method="POST" action="{% url 'ideapeacher:comment' i.pk  %}"> 
	{%csrf_token%}

	<textarea class="form-control" aria_label="With textarea" name="comment" placeholder="Enter comment here"></textarea>

	<button type="submit" id="commentbtn" class="btn">Comment</button>

</form>




{% endfor %}

{% endfor %}

{% endif %}

{% endblock %}

ideapeacher/templates/main/home1.html
{% extends "main/header.html" %}
{% block content %}
{% if ideas %}

{% for i in ideas %}
<p>User: {{i.peacher.user}}</p>
<p>{{i.date_created}}</p>

{% for c in i.category.all %}
	{{c.category}}

	<p>{{i.post_idea}}</p>
	

{% endfor %}

{% endfor %}

{% endif %}
{% endblock %}

ideapeacher/templates/main/idea.html
<head>
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300);
* {
  font-family: 'Open Sans', sans-serif;
}

body {
  margin: 0;
  padding: 0;
  overflow: hidden;
  background: #111;
  background-repeat: no-repeat;
}

.signupSection {
  background: url(https://source.unsplash.com/TV2gg2kZD1o/1600x800);
  background-repeat: no-repeat;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 800px;
  height: 450px;
  text-align: center;
  display: flex;
  color: white;
  box-shadow: 3px 10px 20px 5px rgba(0, 0, 0, .5);
}

.info {
  width: 45%;
  background: rgba(20, 20, 20, .8);
  padding: 30px 0;
  border-right: 5px solid rgba(30, 30, 30, .8);
  h2 {
    padding-top: 30px;
    font-weight: 300;
  }
  p {
    font-size: 18px;
  }
  .icon {
    font-size: 8em;
    padding: 20px 0;
    color: rgba(10, 180, 180, 1);
  }
}

.signupForm {
  width: 70%;
  padding: 30px 0;
  background: rgba(20, 40, 40, .8);
  transition: .2s;
  h2 {
    font-weight: 300;
  }
}

.inputFields {
  margin: 15px 0;
  font-size: 16px;
  padding: 10px;
  width: 250px;
  border: 1px solid rgba(10, 180, 180, 1);
  border-top: none;
  border-left: none;
  border-right: none;
  background: rgba(20, 20, 20, .2);
  color: white;
  outline: none;
}

.noBullet {
  list-style-type: none;
  padding: 0;
}

#join-btn {
  border: 1px solid rgba(10, 180, 180, 1);
  background: rgba(20, 20, 20, .6);
  font-size: 18px;
  color: white;
  margin-top: 20px;
  padding: 10px 50px;
  cursor: pointer;
  transition: .4s;
  &:hover {
    background: rgba(20, 20, 20, .8);
    padding: 10px 80px;
  }
}

</style>

</head>

<div class="signupSection">
  <div class="info">
    <h2>Welcome to IdeaPeacher Website</h2>
    <i class="icon ion-ios-ionic-outline" aria-hidden="true"></i>
    <p>Please Post your ideas here &#128073; &#128073;</p>
  </div>
<form method="POST" action="{% url 'ideapeacher:submitidea' %}"  class="signupForm" enctype="multipart/form-data">
{% csrf_token %}
<h2>Suggest your Idea</h2>
<br>
<ul class="noBullet">
      <li>
        <label for="category">Select Your Category:</label>
        <select name="dropdown" >
		<option value="Technology">Technology</option>
		<option value="Business">Business</option>
		<option value="Health">Health</option>
		<option value="LifeHacks">Life Hacks</option>

	</select>
      </li>
      <li>
        <label for="Idea">Write Down Your Idea:</label>

        <textarea type="text" class="inputFields" id="password" name="idea" placeholder=" Present Your Idea" value="" oninput="return passwordValidation(this.value)" required></textarea>
      </li>
      <li>
        <label for="Pdf">Place Your File:</label>
        <input type="file" class="inputFields" id="email" name="pdf"  value="" required/>
      </li>
      <li id="center-btn">
        <button type="submit" id="join-btn" name="join" alt="Join" value=""> Submit </button>
      </li>
    </ul>
  </form>
</div>

ideapeacher/templates/main/login.html
<html>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    main {
      flex: 1 0 auto;
    }

    body {
      background: #fff;
    }

    .input-field input[type=date]:focus + label,
    .input-field input[type=text]:focus + label,
    .input-field input[type=email]:focus + label,
    .input-field input[type=password]:focus + label {
      color: #e91e63;
    }

    .input-field input[type=date]:focus,
    .input-field input[type=text]:focus,
    .input-field input[type=email]:focus,
    .input-field input[type=password]:focus {
      border-bottom: 2px solid #e91e63;
      box-shadow: none;
    }
  </style>
</head>

<body>
  <div class="section"></div>
  <main>
    <center>
      <div class="section"></div>

      <h5 class="indigo-text">Please, login into your account</h5>
      <div class="section"></div>

      <div class="container">
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

          <form class="col s12" method="post">
          {% csrf_token %}
            <div class='row'>
              <div class='col s12'>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='text' name='username' id='email' />
                <label for='username'>Enter your Username</label>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='password' name='password' id='password' />
                <label for='password'>Enter your password</label>
              </div>
            </div>

            <br />
            <center>
              <div class='row'>
                <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'  value="Login">Login</button>
              </div>
            </center>
          </form>
        </div>
      </div>
      <a href="{% url 'ideapeacher:register' %}">Create account</a>
    </center>

    <div class="section"></div>
    <div class="section"></div>
  </main>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>

</html>

ideapeacher/templates/main/register.html
<html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head
<body>
<section class="vh-100 bg-image" style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.jpg');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account:</h2>

              <form method="post">
			    {% csrf_token %}

                <div class="form-outline mb-4">
				   <label class="form-label" for="form3Example1cg">Enter Your Username</label>
                  <input type="text" id="form3Example1cg" name="username" class="form-control form-control-lg" required />
  
                </div>

                <div class="form-outline mb-4">
				  <label class="form-label" for="form3Example3cg"> Enter Your Email</label>
                  <input type="email" name="email" id="form3Example3cg" class="form-control form-control-lg" required/>

                </div>

                <div class="form-outline mb-4">
				   <label class="form-label" for="form3Example4cg">Enter Your Password</label>
                  <input type="password"  name="password1"  id="form3Example4cg" class="form-control form-control-lg" required/>

                </div>

                <div class="form-outline mb-4">
				   <label class="form-label" for="form3Example4cdg">Confirm your password</label>
                  <input type="password"  name="password2" id="form3Example4cdg" class="form-control form-control-lg" required/>
      
                </div>

                <div class="d-flex justify-content-center">
                  <button type="submit"  class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                </div>

                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{% url 'ideapeacher:login_request' %}" class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>
</html>